import Header from "@/components/app/header-landing";
import Head from "next/head";

export default function LandingLayout(props) {
  return (
    <>
      <Head>
        <title>Genshin Companion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"/>
      </Head>
      <Content>{props.children}</Content>
    </>
  );
} 

function Content(props) {
  return (
    <>
      <div className="px-12 bg-black bg-opacity-90 text-white container-sm min-h-screen mx-auto relative">
        <Header/>
        <div className="pt-24 py-2">
          {props.children}
        </div>
      </div>
    </>
  );
}