import React, { useState, useContext } from "react";
import { BrowserRouter as Router, Switch, Route, Link } from "react-router-dom";
import Head from "next/head";
import Image from 'next/image';
import Home from './home/index';
// import { Modal, modalHandler } from "../components/Modal";
import { Modal } from "../components/Modal";
// import { ModalContext, ModalProvider } from "../contexts/ModalContext";
import { ResinProvider } from "../contexts/ResinContext";
import ResinManager from "./resin-manager";

const getClassList = element => document.getElementById(element).classList;
const addClass = (element, className) => getClassList(element).add(className);
const toggleClass = (element, className) => getClassList(element).toggle(className);
const removeClass = (element, className) => getClassList(element).remove(className);

const toggleNavbar = () => {
  toggleClass('nav-bar', 'expanded');
  toggleClass('app-overlay', 'active');
}

export default function App() {
  const fetchHello = async () => {
    const response = await fetch('http://localhost:3000/api/hello');
    const data = await response.json();
    console.log(data);
  }

  fetchHello();
  return (
    <Router>
      <Head>
        <title>Genshin Companion</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons"
      rel="stylesheet"/>
      </Head>
      <ResinProvider>
        {/* <ModalProvider> */}
          <AppContent/>
        {/* </ModalProvider> */}
      </ResinProvider>
      <div id="portal-1"></div>
      <div id="portal-2"></div>
    </Router>
  );
}

function AppContent(props) {
  // const [modalHandler, modalOpen, modalContent] = useContext(ModalContext);

  return (
    <div className="bg-black bg-opacity-90 text-white container-sm min-h-screen mx-auto relative">
      <AppHeader/>
      {/* <AppHeader modalHandler={modalHandler}/> */}
      <div className="fixed -z-10 top-0 left-0 right-0 bg-transparent min-h-screen" id="app-overlay" onClick={toggleNavbar}>
      </div>
      <NavigationBar/>
      {/* <Modal isActive={modalOpen} closeHandler={modalHandler.close}>
        {modalContent}
      </Modal> */}
      <Switch>
        <Route exact path="/home" component={Home}/>
        <Route exact path="/resin-manager" component={ ResinManager }/>
      </Switch>
    </div>
  );
}

function AppHeader(props) {
  const [openModal, setOpenModal] = useState(false);
  return (
    <header className='flex h-14 items-center justify-between px-3 bg-navbar fixed z-30 top-0 left-0 right-0'>
      <button
        className="opacity-90 material-icons"
        id="navbar-btn"
        onClick={toggleNavbar}
      >
        menu
      </button>
      <Link to="/home"><div className="relative" style={{height: '36px', width: '120px'}}><Image src="/assets/img/Logo.png" layout="fill" objectFit="contain" quality={100}/></div></Link>
      <img
        className="w-8 rounded-full"
        src="https://img-os-static.hoyolab.com/communityWeb/upload/cb31fe8dae809ebdbc72039cba527501.png"
        alt="Profile"
        onClick={() => setOpenModal(true)}
      />
      <Modal isFull= {false} isOpen={openModal} closeHandler={() => setOpenModal(false)}>
        <AccountsModal closeHandler={() => setOpenModal(false)}/>
      </Modal>
    </header>
  );
}

function NavigationBar() {
  const nav_list = [
    {to: '/home', icon:'home', name:'Home', id:'home'},
    {to: '/my-weapons', icon:'home', name:'My Weapons', id:'my-weapons'},
    {to: '/my-characters', icon:'people', name:'My Characters', id:'my-characters'},
    {to: '/resin-manager', icon:'home', name:'Resin Manager', id:'resin-manager'},
    {to: '/settings', icon:'settings', name:'Settings', id:'settings'}
  ]
  return (
    <nav className="fixed z-50 w-9/12 -left-full" id="nav-bar">
      <div className="bg-navbar min-h-screen w-full flex flex-col items-start px-4 py-2">
        <Image className="ml-8 mb-6" src="/assets/img/Logo.png" height={36} width={116}/>
        <ul className="nav-list">
          {
            nav_list.map((nav_item, index) => (
              <li className="nav-item" key={`nav-${index}`}>
                <Link key={nav_item.id} className="flex py-2 text-white text-opacity-60" id={`link-${nav_item.id}`} to={nav_item.to} onClick={toggleNavbar}>
                  <span className="material-icons mr-6">{nav_item.icon}</span><span>{nav_item.name}</span>
                </Link>
              </li>
            ))
          }
        </ul>
        <div className="flex py-2 text-white text-opacity-60 absolute bottom-4 left-4">
          <span className="material-icons mr-6 transform rotate-180">logout</span><span>Logout</span>
        </div>
      </div>
    </nav>
  );
};

function AccountsModal(props) {
  return (
    <div className="bg-navbar p-4 rounded-md" id="accounts-modal">
      <div className="flex items-center mb-3 text-lg text-white text-opacity-80">
        <button className="material-icons mr-8" id="accounts-close" onClick={props.closeHandler}>close</button>
        Accounts
      </div>
      <AccountsModalContent/>
    </div>
  );
}

function AccountsModalContent(props) {
  const accounts = [
    { nickname: 'Tabibito', ar: 55, profile: 'https://img-os-static.hoyolab.com/communityWeb/upload/cb31fe8dae809ebdbc72039cba527501.png'},
    { nickname: 'Lumine', ar: 45, profile: 'https://img-os-static.hoyolab.com/communityWeb/upload/cb31fe8dae809ebdbc72039cba527501.png'},
    { nickname: 'Aether', ar: 33, profile: 'https://img-os-static.hoyolab.com/communityWeb/upload/cb31fe8dae809ebdbc72039cba527501.png'},
    { nickname: 'Diluc', ar: 28, profile: 'https://img-os-static.hoyolab.com/communityWeb/upload/cb31fe8dae809ebdbc72039cba527501.png'},
  ]
  const accountsMenus = [
    { icon: 'person_add', inner: 'Add another accounts'},
    { icon: 'manage_accounts', inner: 'Manage all account on this device'}
  ]
  const [currentAccount, setCurrentAccount] = useState(accounts[0]);
  const [isExpanded, setIsExpanded] = useState(false);

  return (
    <div className={`content${isExpanded ? ' expanded' : ''}`}>
      { <Account
          key={currentAccount.nickname}
          account={currentAccount}
          isCurrent={true}
          handleExpand={() => setIsExpanded(!isExpanded)}
      /> }
      <button className="border border-white border-opacity-30 rounded-full px-3 py-1 ml-14 font-medium tracking-wide text-sm text-white text-opacity-60 whitespace-nowrap" id="manage-account">Manage this account</button>
      { isExpanded ? 
        <>
          <div className="mt-4 ml-14 border-b border-white border-opacity-30"></div>
          { accounts.filter(account => account.nickname !== currentAccount.nickname)
            .map(account => <Account key={account.nickname} account={account}/>) }
          { accountsMenus.map(menu => <div key={menu.icon} className="flex items-center pl-2 py-3 text-white text-opacity-60"><span className="mr-5 material-icons">{menu.icon}</span>{menu.inner}</div>) }
        </> : ''
      }
    </div>
  )
}

function Account(props) {
  return (
    <div className={`account${props.isCurrent ? ' current' : ''} flex items-center py-3`}>
      <img className="w-10 rounded-full mr-4" src={props.account.profile}/>
      <div className="flex flex-col flex-1">
        <div className="font-medium tracking-wider text-white text-opacity-80">{props.account.nickname}</div>
        <div className="text-xs text-white text-opacity-40">Adventure Rank {props.account.ar}</div>
      </div>
      { props.isCurrent ? 
        <button className="text-white text-opacity-60 material-icons border border-white border-opacity-30 rounded-full" id="more-accounts" onClick={props.handleExpand}>expand_more</button>
        :
        <button className="btn btn-primary">Switch</button>
      }
    </div>
  )
}